### ISSUE TITLE
fix: unable to update email on Supabase when changed in the todo app

### ISSUE THREAD

**Issue by nomadEngineer-FUK** [nomadEngineer-FUK/todoapp_2411_nuxt3_with_auth#12]
## 1. Outline
Users need their email registered for login.
While the email can be updated in the app's profile page, the change is not reflected in Supabase's auth system.

## 2. As Is
- Users can change their email on the app's profile page.
- The updated email is not reflected in Supabase's auth system, causing a login failure.

## 3. To Be
- Users can update their email, and the change is synchronized with Supabase's auth system.

## 4. To Do
- [ ] Ensure the email update functionality works seamlessly on Supabase.
- [ ] Synchronize the `auth` email and the `users` table.
- [ ] Test the updated email flow, including the Supabase email verification process.

**Comment by nomadEngineer-FUK** [comment]
misunderstanding
it turns out it doesn't need to fix, but already working
